name: Compile JVM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  windows:
    name: run on windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1.4.1
    - name: compile
      run: | 
        cl /LD /Fejvm.dll jvm.cpp /link user32.lib comdlg32.lib winmm.lib
    - name: upload executable
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: |
          jvm.dll
